name: Send Telegram Notification

on:
  schedule:
    # ุงูุฃุญุฏ ูุงูุฃุฑุจุนุงุก ุงูุณุงุนุฉ 3:00 ุนุตุฑุงู ุจุชูููุช ูุตุฑ
    - cron: '0 13 * * 0,3'
  workflow_dispatch: # ููุชุดุบูู ุงููุฏูู ุงูุขู ููุชุฌุฑุจุฉ

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        run: |
          # ุถุจุท ุชูููุช ูุตุฑ
          export TZ='Africa/Cairo'
          CUR_DATE=$(date +'%Y-%m-%d')
          CUR_TIME=$(date +'%H:%M:%S')
          
          # ุงูุจูุงูุงุช ุงูุฌุฏูุฏุฉ ุงูุฎุงุตุฉ ุจู
          TOKEN="8305317876:AAHkPFr8idftz1Rgc6-tdCugaaZTrQsZnP4"
          CHAT_ID="-5216371452"
          
          # ูุต ุงูุฑุณุงูุฉ
          MESSAGE="๐ *ุฅุดุนุงุฑ ุฌุฏูุฏ*%0A%0A*ุงูุงุณู:* ููู ุงูุฑ ุงูุทุงูุจ ุงุญูุฏ ูุญูุฏ ููุณู%0A*ุงูุชุงุฑูุฎ:* $CUR_DATE%0A*ุงูููุช:* $CUR_TIME"
          
          # ุชูููุฐ ุงูุฅุฑุณุงู
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
          -d "chat_id=$CHAT_ID" \
          -d "text=$MESSAGE" \
          -d "parse_mode=Markdown"
